# Generated by Django 3.0.5 on 2020-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200422_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.CharField(choices=[('adilabad', 'Adilabad'), ('kothagudem', 'Kothagudem'), ('hyderabad', 'Hyderabad'), ('jagitial', 'Jagitial'), ('bhupalpalle', 'Bhupalpalle'), ('gadwal', 'Gadwal'), ('kamareddy', 'Kamareddy'), ('karimnagar', 'Karimnagar'), ('khammam', 'Khammam'), ('komaram bheem', 'Komaram Bheem'), ('mahabubabad', 'Mahabubabad'), ('mahabubnagar', 'Mahabubnagar'), ('mancherial', 'Mancherial'), ('medak', 'Medak'), ('medchal', 'Medchal'), ('mulugu', 'Mulugu'), ('nagarkurnool', 'Nagarkurnool'), ('narayanpet', 'Narayanpet'), ('nalgonda', 'Nalgonda'), ('nirmal', 'Nirmal'), ('nizamabad', 'Nizamabad'), ('peddapalli', 'Peddapalli'), ('sircilla', 'Sircilla'), ('ranga Reddy', 'Ranga Reddy'), ('sangareddy', 'Sangareddy'), ('siddipet', 'Siddipet'), ('suryapet', 'Suryapet'), ('vikarabad', 'Vikarabad'), ('wanaparthy', 'Wanaparthy'), ('warangal', 'Warangal'), ('yadadri bhuvanagiri', 'Yadadri Bhuvanagiri')], default='hyderabad', max_length=20),
        ),
    ]
