# Generated by Django 3.0.5 on 2020-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(choices=[('Telugu', 'Telugu'), ('Hindi', 'Hindi'), ('English', 'English'), ('Malayalam', 'Malayalam'), ('kannada', 'kannada')], default='Telugu', max_length=10),
        ),
    ]
