# Generated by Django 3.0.5 on 2020-04-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20200428_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tickets',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='two', max_length=10),
        ),
    ]
