# Generated by Django 3.0.5 on 2020-04-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200428_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
