# Generated by Django 3.0.5 on 2020-05-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20200429_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.IntegerField(default=150),
            preserve_default=False,
        ),
    ]
